### ISSUE TITLE
New module: TwitchIO

### ISSUE THREAD

**Issue by Samathingamajig** [Darkempire78/Amazing-Python-Modules#2]
**Name :** TwitchIO
**Repository :** https://github.com/TwitchIO/TwitchIO
**Description :** An Async Bot/API wrapper for Twitch made in Python.

**Complete :**
|[Name](link)|Description|Sync/Async|True/False|![](https://img.shields.io/github/last-commit/USER/REPOSITORY?style=for-the-badge&label=)|
| :-: | :- | :-: | :-: | :-: |
| [TwitchIO](https://github.com/TwitchIO/TwitchIO) | An Async Bot/API wrapper for Twitch made in Python. | Async | True | ![](https://img.shields.io/github/last-commit/TwitchIO/TwitchIO?style=for-the-badge&label=) |

**Comment by Darkempire78** [comment]
Added
